package analysis

import (
	"github.com/konveyor/go-konveyor-tests/data"
	"github.com/konveyor/tackle2-hub/api"
)

var DaytraderWithDeps = TC{
	Name:        "Daytrader",
	Application: data.Daytrader,
	WithDeps:    true,
	Task:        Analyze,
	Targets: []string{
		"konveyor.io/target=cloud-readiness",
		"konveyor.io/target=quarkus",
	},
	Analysis: api.Analysis{
		Effort: 10,
		Issues: []api.Issue{
			{
				Category:    "mandatory",
				Description: "File system - Java IO",
				Effort:      1,
				RuleSet:     "cloud-readiness",
				Rule:        "local-storage-00001",
				Incidents: []api.Incident{
					{
						File:    "/shared/source/sample/daytrader-ee7-web/src/main/java/com/ibm/websphere/samples/daytrader/web/TradeScenarioServlet.java",
						Line:    125,
						Message: "An application running inside a container could lose access to a file in local storage.",
					},
				},
			},
			{
				Category:    "mandatory",
				Description: "File system - java.net.URL/URI",
				Effort:      1,
				RuleSet:     "cloud-readiness",
				Rule:        "local-storage-00002",
				Incidents: []api.Incident{
					{
						File:    "/shared/source/sample/daytrader-ee7-web/src/main/java/com/ibm/websphere/samples/daytrader/web/prims/PingReentryServlet.java",
						Line:    91,
						Message: "An application running inside a container could lose access to a file in local storage.",
					},
					{
						File:    "/shared/source/sample/daytrader-ee7-web/src/main/java/com/ibm/websphere/samples/daytrader/web/prims/PingServlet2PDF.java",
						Line:    86,
						Message: "An application running inside a container could lose access to a file in local storage.",
					},
				},
			},
			{
				Category:    "mandatory",
				Description: "Local HTTP Calls",
				Effort:      7,
				RuleSet:     "cloud-readiness",
				Rule:        "localhost-http-00001",
				Incidents: []api.Incident{
					{
						File:    "/shared/source/sample/daytrader-ee7-web/src/main/java/com/ibm/websphere/samples/daytrader/web/prims/PingServlet2PDF.java",
						Line:    85,
						Message: "The app is trying to access local resource by HTTP, please try to migrate the resource to cloud",
					},
				},
			},
		},
		Dependencies: []api.TechDependency{
			{
				Name:     "taglibs.standard",
				Version:  "1.1.1",
				Provider: "java",
			},
			{
				Name:     "org.apache.derby.derby",
				Version:  "10.14.2.0",
				Provider: "java",
			},
			{
				Name:     "net.wasdev.wlp.sample.daytrader-ee7-web",
				Version:  "1.0-SNAPSHOT",
				Provider: "java",
			},
			{
				Name:     "net.wasdev.wlp.sample.daytrader-ee7-ejb",
				Version:  "1.0-SNAPSHOT",
				Provider: "java",
			},
			{
				Name:     "javax.javaee-api",
				Version:  "7.0",
				Provider: "java",
			},
			{
				Name:     "javax.annotation.javax.annotation-api",
				Version:  "1.3.2",
				Provider: "java",
			},
			{
				Name:     "com.sun.mail.javax.mail",
				Version:  "1.5.0",
				Provider: "java",
			},
			{
				Name:     "javax.activation.activation",
				Version:  "1.1",
				Provider: "java",
			},
		},
	},
	AnalysisTags: []api.Tag{
		{Name: "EJB XML", Category: api.Ref{Name: "Bean"}},
		{Name: "Servlet", Category: api.Ref{Name: "HTTP"}},
		{Name: "CDI", Category: api.Ref{Name: "Inversion of Control"}},
		{Name: "JSF", Category: api.Ref{Name: "MVC"}},
		{Name: "Common Annotations", Category: api.Ref{Name: "Other"}},
		{Name: "Properties", Category: api.Ref{Name: "Other"}},
		{Name: "JPA entities", Category: api.Ref{Name: "Persistence"}},
		{Name: "JPA named queries", Category: api.Ref{Name: "Persistence"}},
		{Name: "JPA XML", Category: api.Ref{Name: "Persistence"}},
		{Name: "Persistence units", Category: api.Ref{Name: "Persistence"}},
		{Name: "EJB Timer", Category: api.Ref{Name: "Processing"}},
		{Name: "Java EE JSON-P", Category: api.Ref{Name: "Processing"}},
		{Name: "Bean Validation", Category: api.Ref{Name: "Validation"}},
		{Name: "JSF Page", Category: api.Ref{Name: "Web"}},
		{Name: "JSP Page", Category: api.Ref{Name: "Web"}},
		{Name: "WebSocket", Category: api.Ref{Name: "Web"}},
		{Name: "CDI XML", Category: api.Ref{Name: "Java EE"}},
		{Name: "JPA named queries", Category: api.Ref{Name: "Java EE"}},
		{Name: "JSF", Category: api.Ref{Name: "Embedded"}},
		{Name: "EJB Timer", Category: api.Ref{Name: "Execute"}},
		{Name: "WebSocket", Category: api.Ref{Name: "View"}},
		{Name: "Persistence units", Category: api.Ref{Name: "Store"}},
		{Name: "Bean Validation", Category: api.Ref{Name: "Java EE"}},
		{Name: "JPA XML", Category: api.Ref{Name: "Store"}},
		{Name: "JPA entities", Category: api.Ref{Name: "Store"}},
		{Name: "JSF XML", Category: api.Ref{Name: "Web"}},
		{Name: "EJB Timer", Category: api.Ref{Name: "Java EE"}},
		{Name: "JPA entities", Category: api.Ref{Name: "Java EE"}},
		{Name: "JSF Page", Category: api.Ref{Name: "Java EE"}},
		{Name: "JSP Page", Category: api.Ref{Name: "Java EE"}},
		{Name: "Common Annotations", Category: api.Ref{Name: "Java EE"}},
		{Name: "EJB XML", Category: api.Ref{Name: "Java EE"}},
		{Name: "EJB XML", Category: api.Ref{Name: "Connect"}},
		{Name: "CDI XML", Category: api.Ref{Name: "Execute"}},
		{Name: "Java EE JSON-P", Category: api.Ref{Name: "Execute"}},
		{Name: "JPA named queries", Category: api.Ref{Name: "Store"}},
		{Name: "JSF XML", Category: api.Ref{Name: "View"}},
		{Name: "Servlet", Category: api.Ref{Name: "Connect"}},
		{Name: "CDI", Category: api.Ref{Name: "Execute"}},
		{Name: "Common Annotations", Category: api.Ref{Name: "Connect"}},
		{Name: "Java EE JSON-P", Category: api.Ref{Name: "Java EE"}},
		{Name: "JSF", Category: api.Ref{Name: "View"}},
		{Name: "JSF Page", Category: api.Ref{Name: "View"}},
		{Name: "CDI XML", Category: api.Ref{Name: "Inversion of Control"}},
		{Name: "CDI", Category: api.Ref{Name: "Java EE"}},
		{Name: "Properties", Category: api.Ref{Name: "Embedded"}},
		{Name: "JSP Page", Category: api.Ref{Name: "View"}},
		{Name: "JPA XML", Category: api.Ref{Name: "Java EE"}},
		{Name: "Properties", Category: api.Ref{Name: "Sustain"}},
		{Name: "Persistence units", Category: api.Ref{Name: "Java EE"}},
		{Name: "Bean Validation", Category: api.Ref{Name: "Store"}},
		{Name: "JSF XML", Category: api.Ref{Name: "Java EE"}},
		{Name: "Servlet", Category: api.Ref{Name: "Java EE"}},
		{Name: "WebSocket", Category: api.Ref{Name: "Java EE"}},
	},
}
