name: Test TIER2

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

jobs:
  test-tier2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: start-minikube
        uses: konveyor/tackle2-operator/.github/actions/start-minikube@main
        with:
          memory: 6500M
      - name: install-tackle
        uses: konveyor/tackle2-operator/.github/actions/install-tackle@main
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install dependencies
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo
      - name: Run tests
        run: HUB_BASE_URL="http://$(minikube ip)/hub" DEBUG=1 make test-tier2 | tee /tmp/tests.log
      - name: Prepare summary
        if: always()
        run: cat /tmp/tests.log | grep -- --- >> $GITHUB_STEP_SUMMARY
      - name: Upload analysis tests output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: analysis-tests-output
          include-hidden-files: true
          path: analysis/tmp_output
