name: Test nightly TIER0

on:
  schedule:
    - cron: "14 1,13 * * *"

jobs:
  test-tier0:
    uses: konveyor/ci/.github/workflows/global-ci-bundle.yml@main
    with:
      operator_bundle: quay.io/konveyor/tackle2-operator-bundle:latest
      run_api_tests: true
      run_ui_tests: false
      api_tests_tiers: DEBUG=1 make test-tier0
