name: Test nightly TIER0

on:
  schedule:
    - cron: '14 1,13 * * *'
      
jobs:
  test-tier0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: start-minikube
        uses: konveyor/tackle2-operator/.github/actions/start-minikube@main
        with:
          memory: 6500M
      - name: install-tackle
        uses: konveyor/tackle2-operator/.github/actions/install-tackle@main
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install dependencies
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo
      - run: HUB_BASE_URL="http://$(minikube ip)/hub" DEBUG=1 make test-tier0
